#!/bin/sh

downloadrepos() {
    github_repo="$1"; shift
    branch="$1"; shift

    wget --quiet --output-document - \
        $github_repo/archive/${branch}.tar.gz | tar xz
}

downloadgithubrepos() {
    repo_owner="$1"; shift
    repo_name="$1"; shift
    repo_branch="$1"; shift
    set -x
    # clean up other previously downloaded branches of the same repo as well
    rm -rf ${repo_name}-*
    ls | grep $repo_name
    downloadrepos https://github.com/$repo_owner/$repo_name $repo_branch
    ls | grep $repo_name
    set +x
}

. ./default_build_params

if [ -z "$1" ]; then
    downloadgithubrepos Ouranosinc pavics-sdi $PAVICS_SDI_BRANCH
    downloadgithubrepos bird-house finch $FINCH_BRANCH
    downloadgithubrepos Ouranosinc raven $RAVEN_BRANCH
    downloadgithubrepos ESGF esgf-compute-api $ESGF_COMPUTE_API_BRANCH
else
    set -x
    downloadrepos "$@"
fi
