#!/bin/sh -x

if [ -z "$DOCKER_IMAGE" ]; then
    DOCKER_IMAGE="pavics/workflow-tests:190503"
fi

UID="`id -u`"
GID="`id -g`"

# launch with current user UID and GID to not have write permission problems
docker run -it --rm --name birdy \
    -v `pwd`:`pwd` -u 0:0 -w `pwd` $DOCKER_IMAGE \
    bash -c "groupmod -g $GID jenkins; \
             usermod -u $UID jenkins; \
             echo 'ENV_PATH PATH=/usr/local/envs/birdy/bin:/opt/conda/bin:/usr/local/bin:/usr/bin:/bin' >> /etc/login.defs; \
             su jenkins -s /bin/bash"
