#!/bin/sh -x

PORT="$1"

if [ -z "$PORT" ]; then
    PORT=8890
fi

IMAGE="pavics/workflow-tests:latest"

# 1000 is the jenkins user inside the image
docker run -u 1000:1000 --rm --name birdy-notebook -p $PORT:$PORT -v `pwd`:`pwd` $IMAGE jupyter notebook --ip=0.0.0.0 --port=$PORT --no-browser
