#!/bin/sh -x

PORT="$1"

if [ -z "$PORT" ]; then
    PORT=8890
fi

if [ -z "$DOCKER_IMAGE" ]; then
    DOCKER_IMAGE="pavics/workflow-tests:190506"
fi

UID="`id -u`"
GID="`id -g`"

# launch with current user UID and GID to not have write permission problems
docker run --rm --name birdy-notebook \
    -p $PORT:$PORT -u 0:0 -v `pwd`:`pwd` $DOCKER_IMAGE \
    bash -c "groupmod -g $GID jenkins; \
             usermod -u $UID jenkins; \
             echo 'ENV_PATH PATH=/usr/local/envs/birdy/bin:/opt/conda/bin:/usr/local/bin:/usr/bin:/bin' >> /etc/login.defs; \
             su jenkins -s /bin/bash -c \
                 'jupyter notebook --ip=0.0.0.0 --port=$PORT --no-browser'"
