#!/bin/sh -x

IMAGE="pavics/workflow-tests:190312.1"

UID="`id -u`"
GID="`id -g`"

# launch with current user UID and GID to not have write permission problems
docker run -it --rm --name birdy \
    -v `pwd`:`pwd` -w `pwd` $IMAGE \
    bash -c "groupmod -g $GID jenkins; \
             usermod -u $UID jenkins; \
             echo 'ENV_PATH PATH=/usr/local/envs/birdy/bin:/opt/conda/bin:/usr/local/bin:/usr/bin:/bin' >> /etc/login.defs; \
             su jenkins -s /bin/bash"
