#!/bin/sh

. ./default_build_params

mv -v pavics-sdi-$PAVICS_SDI_BRANCH/docs/source/notebooks/*.ipynb ./
rm -rfv pavics-sdi-$PAVICS_SDI_BRANCH

mv -v finch-$FINCH_BRANCH/docs/source/notebooks/*.ipynb ./
rm -rfv finch-$FINCH_BRANCH
