#!/bin/sh

. ./default_build_params

# if name clash, last command wins

mv -v esgf-compute-api-$ESGF_COMPUTE_API_BRANCH/examples ./esgf-compute-api-examples-$ESGF_COMPUTE_API_BRANCH
rm -rfv esgf-compute-api-$ESGF_COMPUTE_API_BRANCH

mv -v pavics-sdi-$PAVICS_SDI_BRANCH/docs/source/notebooks/*.ipynb ./
rm -rfv pavics-sdi-$PAVICS_SDI_BRANCH

mv -v finch-$FINCH_BRANCH/docs/source/notebooks/*.ipynb ./
rm -rfv finch-$FINCH_BRANCH
